services:
  n8n-worker:
    image: n8nio/n8n
    network_mode: host
    restart: always
    command: worker
    env_file:
      - ../.env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST_IP}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=${REDIS_HOST_IP}
      - QUEUE_BULL_REDIS_PORT=${REDIS_PORT}
    volumes:
      - n8n_worker_data:/home/node/.n8n
      - n8n_worker_logs:/logs
    deploy:
      placement:
        constraints:
          - "node.labels.role.worker == true"

volumes:
  n8n_worker_data:
  n8n_worker_logs:
