services:
  postgres:
    image: postgres:14
    network_mode: host
    restart: always
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      placement:
        constraints:
          - "node.labels.role.database == true"

volumes:
  postgres_data:
