services:
  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ../.env
    command:
      # Cukup beritahu Traefik untuk menggunakan file konfigurasi statis
      - "--configFile=/etc/traefik/traefik.yml"
    volumes:
      # Mount file konfigurasi yang baru kita buat ke dalam kontainer
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      # Volume untuk menyimpan sertifikat SSL
      - letsencrypt:/letsencrypt
      # Volume untuk koneksi ke Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true

volumes:
  letsencrypt:
