# /proxy-traefik/traefik.yml

# Konfigurasi entry points (HTTP & HTTPS)
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Aktifkan API dashboard (untuk debugging)
api:
  insecure: true

# Aktifkan provider Docker agar bisa mendeteksi kontainer lain
providers:
  docker:
    exposedByDefault: false

# Konfigurasi Certificate Resolver untuk SSL
certificatesResolvers:
  myresolver:
    acme:
      # Gunakan variabel SSL_EMAIL yang dimuat dari .env
      email: "${SSL_EMAIL}"
      storage: "/letsencrypt/acme.json"
      # Pilih salah satu ACME server di bawah ini (Google CA direkomendasikan)
      # caServer: "https://acme-v02.api.letsencrypt.org/directory"
      caServer: "https://dv.acme-v02.api.pki.goog/directory"
      tlsChallenge: {}
