services:
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - n8n-network
    deploy:
      placement:
        constraints:
          - "node.labels.role.redis == true"

networks:
  n8n-network:
    external: true

volumes:
  redis_data:
