services:
  redis:
    image: redis:6.2-alpine
    network_mode: host
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - n8n-network
    deploy:
      placement:
        constraints:
          - "node.labels.role.redis == true"

volumes:
  redis_data:
