services:
  n8n-main:
    image: n8nio/n8n
    restart: always
    env_file:
      - ../.env
    environment:
      - DB_POSTGRESDB_PORT=5432
      - DB_TYPE=postgresdb
      - DOMAIN_NAME
      - EXECUTIONS_MODE=queue
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - QUEUE_BULL_REDIS_HOST=redis
      - SUBDOMAIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    expose:
      - 5678
    volumes:
      - n8n_main_logs:/logs
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true

volumes:
  n8n_main_logs: